services:
  db:
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_DATABASE: 'cdc_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    network_mode: host
    environment:
      rabbitmq_uri: amqp://guest:guest127.0.0.1:5672
    depends_on: 
      - rabbitmq_server
      - redis
      
volumes:
  my-db:
  redis-data: